language: go
go:
  - "1.11"

sudo: false

addons:
  apt:
    packages:
      - tree

before_script:
  - export TZ=Asia/Tokyo

before_install:
  - go get -u github.com/golang/dep/cmd/dep

install:
  - dep ensure

jobs:
  include:
    - stage: test
      script:
        - go test -v ./...
    - stage: deploy
      script:
        - go run main.go
        - tree ./www/api/
        - bash ./scripts/deploy.sh


notifications:
  email: false
