language: go
go:
  - "1.11"

before_install:
  - go get -u github.com/golang/dep/cmd/dep

install:
  - dep ensure

jobs:
  include:
    - stage: test
      script:
        - go test -v ./...
    - stage: deploy
      script:
        - go run main.go
      after_success:
        - bash ./scripts/deploy.sh


notifications:
  email: false
