version: '3'

services:
  app:
    build: .
    volumes:
      - .:/go/src/github.com/shooontan/seiyu5off
      - /go/src/github.com/shooontan/seiyu5off/vendor
    tty: true
    container_name: seiyu5off
