[[constraint]]
  name = "github.com/PuerkitoBio/goquery"
  version = "1.4.1"

[[constraint]]
  name = "github.com/tkuchiki/faketime"
  version = "0.1.0"

[prune]
  go-tests = true
  unused-packages = true
