version: 2

jobs:
  build:
    docker:
      - image: circleci/golang:1.11
    working_directory: /go/src/github.com/shooontan/seiyu5off
    environment:
      TZ: Asia/Tokyo
    steps:
      - checkout
      - run:
          name: go get
          command: |
              go get -u github.com/golang/dep/cmd/dep
              dep ensure
      - run:
          name: go run
          command: go run main.go
      - save_cache:
          key: seiyu5off-{{ epoch }}
          paths:
            - /go/src/github.com/shooontan/seiyu5off/dist
  deploy:
    docker:
      - image: circleci/golang:1.11
    working_directory: /go/src/github.com/shooontan/seiyu5off
    steps:
      - restore_cache:
          keys:
            - seiyu5off
      - add_ssh_keys:
          fingerprints:
            - "61:80:89:17:9d:cf:7a:4c:29:6c:14:f5:08:b3:01:02"
      - run:
          name: git config
          command: |
              mkdir -p ~/.ssh
              echo -e "host github.com \n StrictHostKeyChecking no" >> ~/.ssh/config
              git config --global user.name "CircleCi"
              git config --global user.email "logo.bee.doo19@gmail.com"
      - run: git clone git@github.com:shooontan/seiyu5off.git
      - run:
          name: git deploy if diff exists
          pwd: seiyu5off
          command: |
              mkdir -p dist/api
              cp -ar ../dist/api/* ./dist/api
              git add .
              if [[ $(git diff --cached) ]]; then
                git commit -m ":calendar:by CircleCi [ci skip]"
                git push origin master
              else
                echo "nothing to commit, working tree clean"
              fi
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
  build_and_deploy_cron:
    jobs:
      - build
      - deploy:
          requires:
            - build
    triggers:
      - schedule:
          cron: "0 0 1 * *" # UTC
          filters:
            branches:
              only: master
